//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scr.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start screensaver.
        /// </summary>
        internal static string BrowserUpdateRequiredCaption {
            get {
                return ResourceManager.GetString("BrowserUpdateRequiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use screensaver you should have at least Internet Explorer 10.
        ///Click Help button to proceed to Internet Explorer download page..
        /// </summary>
        internal static string BrowserUpdateRequiredMessage {
            get {
                return ResourceManager.GetString("BrowserUpdateRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://windows.microsoft.com/en-us/internet-explorer/download-ie.
        /// </summary>
        internal static string BrowserUpdateRequiredUrl {
            get {
                return ResourceManager.GetString("BrowserUpdateRequiredUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screensaver.
        /// </summary>
        internal static string ConfigurationCaption {
            get {
                return ResourceManager.GetString("ConfigurationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screensaver does not have configuration..
        /// </summary>
        internal static string ConfigurationMessage {
            get {
                return ResourceManager.GetString("ConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to init extracted content.
        /// </summary>
        internal static string ContentCreateMessage {
            get {
                return ResourceManager.GetString("ContentCreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get parent window size.
        /// </summary>
        internal static string DockAsChildGetClientRectMessage {
            get {
                return ResourceManager.GetString("DockAsChildGetClientRectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to dock window as child one.
        /// </summary>
        internal static string DockAsChildMessage {
            get {
                return ResourceManager.GetString("DockAsChildMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set parent window.
        /// </summary>
        internal static string DockAsChildSetParentMessage {
            get {
                return ResourceManager.GetString("DockAsChildSetParentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set window as child one.
        /// </summary>
        internal static string DockAsChildSetWindowChildMessage {
            get {
                return ResourceManager.GetString("DockAsChildSetWindowChildMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to position window.
        /// </summary>
        internal static string DockAsChildSizeLocationMessage {
            get {
                return ResourceManager.GetString("DockAsChildSizeLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to init archived content.
        /// </summary>
        internal static string ExtractContentArchiveArchiveMessage {
            get {
                return ResourceManager.GetString("ExtractContentArchiveArchiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract archived content.
        /// </summary>
        internal static string ExtractContentArchiveOperationsMessage {
            get {
                return ResourceManager.GetString("ExtractContentArchiveOperationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to handle archived content.
        /// </summary>
        internal static string ExtractContentArchiveUnknownMessage {
            get {
                return ResourceManager.GetString("ExtractContentArchiveUnknownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to init embedded content.
        /// </summary>
        internal static string LoadContentArchiveBytesMessage {
            get {
                return ResourceManager.GetString("LoadContentArchiveBytesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse embedded content.
        /// </summary>
        internal static string LoadContentArchiveOperationsMessage {
            get {
                return ResourceManager.GetString("LoadContentArchiveOperationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to handle embedded content.
        /// </summary>
        internal static string LoadContentArchiveUnknownMessage {
            get {
                return ResourceManager.GetString("LoadContentArchiveUnknownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract resources content.
        /// </summary>
        internal static string LoadContentBytesCopyBytesMessage {
            get {
                return ResourceManager.GetString("LoadContentBytesCopyBytesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find resources content.
        /// </summary>
        internal static string LoadContentBytesFindResourceMessage {
            get {
                return ResourceManager.GetString("LoadContentBytesFindResourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract resources content.
        /// </summary>
        internal static string LoadContentBytesOperationsMessage {
            get {
                return ResourceManager.GetString("LoadContentBytesOperationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to handle resources content.
        /// </summary>
        internal static string LoadContentBytesUnknownMessage {
            get {
                return ResourceManager.GetString("LoadContentBytesUnknownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load content.
        /// </summary>
        internal static string LoadContentErrorCaption {
            get {
                return ResourceManager.GetString("LoadContentErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screensaver.
        /// </summary>
        internal static string PreviewCaption {
            get {
                return ResourceManager.GetString("PreviewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to screensaver initialize preview.
        /// </summary>
        internal static string PreviewMessage {
            get {
                return ResourceManager.GetString("PreviewMessage", resourceCulture);
            }
        }
    }
}
