//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrGen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrGen.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write screensaver module
        ///{0}
        ///{1}.
        /// </summary>
        internal static string ExtractModuleFileWrite {
            get {
                return ResourceManager.GetString("ExtractModuleFileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load screensaver module
        ///{0}.
        /// </summary>
        internal static string ExtractModuleLoadResourceBytes {
            get {
                return ResourceManager.GetString("ExtractModuleLoadResourceBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read caption file
        ///{0}
        ///{1}.
        /// </summary>
        internal static string InjectCaptionFileRead {
            get {
                return ResourceManager.GetString("InjectCaptionFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create archive from content directory
        ///{0}
        ///{1}
        ///{2}.
        /// </summary>
        internal static string InjectContentCreateArchive {
            get {
                return ResourceManager.GetString("InjectContentCreateArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete archive
        ///{0}
        ///{1}.
        /// </summary>
        internal static string InjectContentDeleteArchive {
            get {
                return ResourceManager.GetString("InjectContentDeleteArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get temporary file path
        ///{0}.
        /// </summary>
        internal static string InjectContentGetTemp {
            get {
                return ResourceManager.GetString("InjectContentGetTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read archive
        ///{0}
        ///{1}.
        /// </summary>
        internal static string InjectContentReadArchive {
            get {
                return ResourceManager.GetString("InjectContentReadArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read icon file
        ///{0}
        ///{1}.
        /// </summary>
        internal static string InjectIconFileRead {
            get {
                return ResourceManager.GetString("InjectIconFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse ico file
        ///{0}
        ///{1}.
        /// </summary>
        internal static string InjectIconParseICO {
            get {
                return ResourceManager.GetString("InjectIconParseICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save icon to file
        ///{0}
        ///{1}.
        /// </summary>
        internal static string InjectIconPEToFile {
            get {
                return ResourceManager.GetString("InjectIconPEToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to begin update resource
        ///{0}
        ///{1}.
        /// </summary>
        internal static string InjectResourceBeginUpdateResource {
            get {
                return ResourceManager.GetString("InjectResourceBeginUpdateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete update resource
        ///{0}
        ///{1}.
        /// </summary>
        internal static string InjectResourceCompleteUpdateResource {
            get {
                return ResourceManager.GetString("InjectResourceCompleteUpdateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update resource
        ///{0}
        ///{1}.
        /// </summary>
        internal static string InjectResourceUpdateResource {
            get {
                return ResourceManager.GetString("InjectResourceUpdateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting module....
        /// </summary>
        internal static string MainExtractModule {
            get {
                return ResourceManager.GetString("MainExtractModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injecting caption....
        /// </summary>
        internal static string MainInjectCaption {
            get {
                return ResourceManager.GetString("MainInjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injecting content....
        /// </summary>
        internal static string MainInjectContent {
            get {
                return ResourceManager.GetString("MainInjectContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injecting icon....
        /// </summary>
        internal static string MainInjectIcon {
            get {
                return ResourceManager.GetString("MainInjectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screensaver successfully saved.
        ///{0}.
        /// </summary>
        internal static string MainSuccess {
            get {
                return ResourceManager.GetString("MainSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating arguments....
        /// </summary>
        internal static string MainValidateArgs {
            get {
                return ResourceManager.GetString("MainValidateArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates Win32 screensaver from web content.
        ///
        ///SCRGEN src [cap] [ico] out
        ///
        ///  src  web content directory path   (with &quot;index.html&quot;)
        ///  cap  caption file path            (UTF-8 TXT)
        ///  ico  icon file path               (ICO)
        ///  out  output screensaver file path (SCR)
        ///  
        ///Application will try to use &quot;caption.txt&quot; and &quot;icon.ico&quot; files as caption and icon of screensaver from parent directory of &lt;src&gt; and &lt;src&gt; directory itself if [cap] and [ico] arguments are not specified..
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption file does not exist
        ///{0}.
        /// </summary>
        internal static string ValidateArgsCaptionFile {
            get {
                return ResourceManager.GetString("ValidateArgsCaptionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content file does not exist
        ///{0}.
        /// </summary>
        internal static string ValidateArgsContentFile {
            get {
                return ResourceManager.GetString("ValidateArgsContentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon file does not exist
        ///{0}.
        /// </summary>
        internal static string ValidateArgsIconFile {
            get {
                return ResourceManager.GetString("ValidateArgsIconFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file already exists
        ///{0}.
        /// </summary>
        internal static string ValidateArgsOutputFile {
            get {
                return ResourceManager.GetString("ValidateArgsOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory does not exist
        ///{0}.
        /// </summary>
        internal static string ValidateArgsSourceDirectory {
            get {
                return ResourceManager.GetString("ValidateArgsSourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write file
        ///{0}
        ///{1}.
        /// </summary>
        internal static string WriteOutputFileWrite {
            get {
                return ResourceManager.GetString("WriteOutputFileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update icon
        ///{0}
        ///{1}.
        /// </summary>
        internal static string WriteOutputUpdateMainIcon {
            get {
                return ResourceManager.GetString("WriteOutputUpdateMainIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update string table
        ///{0}
        ///{1}.
        /// </summary>
        internal static string WriteOutputUpdateStringTable {
            get {
                return ResourceManager.GetString("WriteOutputUpdateStringTable", resourceCulture);
            }
        }
    }
}
