using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Web Screensaver")]
[assembly: AssemblyDescription("Generated by WebSaver: web screensaver generator")]
//[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("https://github.com/vitalyobukhov/WebSaver")]
[assembly: AssemblyProduct("Web Screensaver")]
//[assembly: AssemblyCopyright("Copyright ©  2013")]
//[assembly: AssemblyTrademark("")]
//[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]
[assembly: Guid("85134cb5-990d-4fb4-9d3c-103a6e655d4e")]

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
